[settings]
endpoint = "https://staging.suttacentral.net/api/search/instant"

[defaults]
limit = 10
site-language = "en"
restrict = "all"
match-partial = false
selected-languages = ["en", "pli"]

[[test-case]]
description = "Find volpage:SN ii 4"
query = "volpage:SN ii 4"
expected.suttaplex = "sn12.3"

[[test-case]]
description = "`by:sabbamitta+Katze` finds an5.99"
query = "by:sabbamitta Katze"
selected-languages = ["de"]
expected.sutta = "/an5.99/de/sabbamitta"
