[settings]
endpoint = "https://staging.suttacentral.net/api/search/instant"

[defaults]
limit = 10
site-language = "en"
restrict = "all"
match-partial = false
selected-languages = ["en", "pli"]

[[test-case]]
description = "Find volpage:SN ii 4"
query = "volpage:SN ii 4"
expected.volpage = "PTS SN ii 1"

[[test-case]]
description = "Find and rank volpage:SN ii 4"
query = "volpage:SN ii 4"
expected.volpage = "PTS SN ii 4"
expected.min-rank = 3